import { gql } from '@/__generated__';

export const STOCKTAKE_LIST = gql(`query FranchiseStocktakes($storeId:ID!,$status:StocktakeStatus,$listingId:ID,$batchId:ID,$hasDifference:Boolean,$from:Time,$to:Time,$page:Int!,$perPage:Int!){franchiseStocktakes(storeId:$storeId,status:$status,listingId:$listingId,batchId:$batchId,hasDifference:$hasDifference,from:$from,to:$to,page:$page,perPage:$perPage,includeHistory:false){data{id status startedAt lines{id countedQuantity snapshotQuantity difference needsRecount}} total currentPage perPage}}`);
export const STOCKTAKE_DETAIL = gql(`query FranchiseStocktake($storeId:ID!,$id:ID!){franchiseStocktake(storeId:$storeId,id:$id){id storeId status startedAt reviewedAt postedAt canceledAt initiatedByAccountId postedById addLineChoices{batchId packageId packageName packageEnabled} lines{id batchId listingId batchNumber expiresAt packageId packageName packageSetVersion packageEnabled countedQuantity snapshotQuantity difference reasonCode reasonNote countHistory{actorAccountId countedQuantity countedAt} needsRecount}}}`);
export const STOCKTAKE_BATCH_CHOICES = gql(`query FranchiseStocktakeBatchChoices($storeId:ID!,$listingId:ID!,$page:Int!,$perPage:Int!){franchiseStocktakeBatchChoices(storeId:$storeId,listingId:$listingId,page:$page,perPage:$perPage){data{id listingId batchNumber expiresAt} total currentPage perPage}}`);
export const CREATE_STOCKTAKE = gql(`mutation FranchiseCreateStocktake($input:FranchiseCreateStocktakeInput!){franchiseCreateStocktake(input:$input){id status}}`);
export const ADD_STOCKTAKE_LINE = gql(`mutation FranchiseAddStocktakeLine($storeId:ID!,$id:ID!,$batchId:ID!,$packageId:ID!){franchiseAddStocktakeLine(storeId:$storeId,id:$id,batchId:$batchId,packageId:$packageId){id status}}`);
export const RECORD_STOCKTAKE_LINE = gql(`mutation FranchiseRecordStocktakeLine($storeId:ID!,$id:ID!,$lineId:ID!,$quantity:Int!){franchiseRecordStocktakeLine(storeId:$storeId,id:$id,lineId:$lineId,quantity:$quantity){id status}}`);
export const SUBMIT_STOCKTAKE = gql(`mutation FranchiseSubmitStocktake($storeId:ID!,$id:ID!){franchiseSubmitStocktake(storeId:$storeId,id:$id){id status}}`);
export const SET_STOCKTAKE_REASON = gql(`mutation FranchiseSetStocktakeReason($storeId:ID!,$id:ID!,$lineId:ID!,$reasonCode:String!,$note:String){franchiseSetStocktakeReason(storeId:$storeId,id:$id,lineId:$lineId,reasonCode:$reasonCode,note:$note){id status}}`);
export const RETURN_STOCKTAKE = gql(`mutation FranchiseReturnStocktake($storeId:ID!,$id:ID!){franchiseReturnStocktake(storeId:$storeId,id:$id){id status}}`);
export const CANCEL_STOCKTAKE = gql(`mutation FranchiseCancelStocktake($storeId:ID!,$id:ID!){franchiseCancelStocktake(storeId:$storeId,id:$id){id status}}`);
export const POST_STOCKTAKE = gql(`mutation FranchisePostStocktake($storeId:ID!,$id:ID!){franchisePostStocktake(storeId:$storeId,id:$id){id status}}`);
