package tools

import (
	"base-engine/auth"
	"base-engine/src/services/ai"
)

func productReadSpecs() []ai.ToolSpec {
	const hq, franchise = auth.WorkspaceTypeHeadquarters, auth.WorkspaceTypeFranchise
	barcode := reviewedSpec("FranchiseStockPackageByBarcode", "graphql.query.franchiseStockPackageByBarcode", `query FranchiseStockPackageByBarcode($storeId:ID!,$barcode:String!){franchiseStockPackageByBarcode(storeId:$storeId,barcode:$barcode){status target{productName skuId skuName listingId packageId packageName barcode packageSetVersion conversionChain{packageId name containsQuantity baseQuantity}}}}`, ai.ModeReadOnly, "LOW", "franchiseStock:read", franchise, "", nil, []string{"storeId", "barcode"})
	barcode.ScopeFields = []string{"storeId"}
	return append([]ai.ToolSpec{
		barcode,
		reviewedSpec("HqGenerateProductPackageBarcode", "graphql.query.hqGenerateProductPackageBarcode", `query HqGenerateProductPackageBarcode{hqGenerateProductPackageBarcode}`, ai.ModeReadOnly, "LOW", "hqProductCatalog:manage", hq, "", nil, nil),
		reviewedSpec("HqProductCategories", "graphql.query.hqProductCategories", `query HqProductCategories($q:String,$enabled:Boolean,$parentId:ID,$page:Int!,$perPage:Int!){hqProductCategories(q:$q,enabled:$enabled,parentId:$parentId,page:$page,perPage:$perPage){data{id name parentId enabled sortOrder} total currentPage perPage}}`, ai.ModeReadOnly, "LOW", "hqProductCatalog:read", hq, "", nil, []string{"q", "enabled", "parentId", "page", "perPage"}),
		reviewedSpec("HqProducts", "graphql.query.hqProducts", `query HqProducts($categoryId:ID,$brandId:ID,$q:String,$enabled:Boolean,$page:Int!,$perPage:Int!){hqProducts(categoryId:$categoryId,brandId:$brandId,q:$q,enabled:$enabled,page:$page,perPage:$perPage){data{id name categoryId brandId brand description defaultPackageTemplateId selectedValueIds enabled} total currentPage perPage}}`, ai.ModeReadOnly, "LOW", "hqProductCatalog:read", hq, "", nil, []string{"categoryId", "brandId", "q", "enabled", "page", "perPage"}),
		reviewedSpec("HqProductSkus", "graphql.query.hqProductSkus", `query HqProductSkus($productId:ID!,$q:String,$enabled:Boolean,$page:Int!,$perPage:Int!){hqProductSkus(productId:$productId,q:$q,enabled:$enabled,page:$page,perPage:$perPage){data{id productId name valueIds shelfLifeDays publishedPackageSetVersion enabled selectionRetired} total currentPage perPage}}`, ai.ModeReadOnly, "LOW", "hqProductCatalog:read", hq, "", nil, []string{"productId", "q", "enabled", "page", "perPage"}),
		reviewedSpec("HqProductPackages", "graphql.query.hqProductPackages", `query HqProductPackages($skuId:ID!,$q:String,$enabled:Boolean,$page:Int!,$perPage:Int!){hqProductPackages(skuId:$skuId,q:$q,enabled:$enabled,page:$page,perPage:$perPage){data{id skuId name barcode packageSetVersion containsPackageId containsQuantity suggestedPriceFen enabled} total currentPage perPage}}`, ai.ModeReadOnly, "LOW", "hqProductCatalog:read", hq, "", nil, []string{"skuId", "q", "enabled", "page", "perPage"}),
		reviewedSpec("FranchiseCatalog", "graphql.query.franchiseCatalog", `query FranchiseCatalog($storeId:ID!,$q:String,$categoryId:ID,$listingEnabled:Boolean,$published:Boolean,$page:Int!,$perPage:Int!){franchiseCatalog(storeId:$storeId,q:$q,categoryId:$categoryId,listingEnabled:$listingEnabled,published:$published,page:$page,perPage:$perPage){data{id productId name published listingId listingEnabled} total currentPage perPage}}`, ai.ModeReadOnly, "LOW", "franchiseProduct:read", franchise, "", nil, []string{"storeId", "q", "categoryId", "listingEnabled", "published", "page", "perPage"}),
		reviewedSpec("FranchiseCatalogCategories", "graphql.query.franchiseCatalogCategories", `query FranchiseCatalogCategories($storeId:ID!,$page:Int!,$perPage:Int!){franchiseCatalogCategories(storeId:$storeId,page:$page,perPage:$perPage){data{id name parentId} total currentPage perPage}}`, ai.ModeReadOnly, "LOW", "franchiseProduct:read", franchise, "", nil, []string{"storeId", "page", "perPage"}),
		reviewedSpec("FranchiseMerchandisingStores", "graphql.query.franchiseMerchandisingStores", `query FranchiseMerchandisingStores($page:Int!,$perPage:Int!){franchiseMerchandisingStores(page:$page,perPage:$perPage){data{id name} total currentPage perPage}}`, ai.ModeReadOnly, "LOW", "franchiseProduct:read", franchise, "", nil, []string{"page", "perPage"}),
		reviewedSpec("FranchiseStoreListings", "graphql.query.franchiseStoreListings", `query FranchiseStoreListings($storeId:ID!,$page:Int!,$perPage:Int!){franchiseStoreListings(storeId:$storeId,page:$page,perPage:$perPage){data{id storeId skuId enabled selectedAt} total currentPage perPage}}`, ai.ModeReadOnly, "LOW", "franchiseProduct:read", franchise, "", nil, []string{"storeId", "page", "perPage"}),
		reviewedSpec("FranchiseStoreOffers", "graphql.query.franchiseStoreOffers", `query FranchiseStoreOffers($storeId:ID!,$listingId:ID!,$packageId:ID,$enabled:Boolean,$page:Int!,$perPage:Int!){franchiseStoreOffers(storeId:$storeId,listingId:$listingId,packageId:$packageId,enabled:$enabled,page:$page,perPage:$perPage){data{id listingId packageId priceFen enabled} total currentPage perPage}}`, ai.ModeReadOnly, "LOW", "franchiseProduct:read", franchise, "", nil, []string{"storeId", "listingId", "packageId", "enabled", "page", "perPage"}),
		reviewedSpec("FranchiseOfferPriceRevisions", "graphql.query.franchiseOfferPriceRevisions", `query FranchiseOfferPriceRevisions($storeId:ID!,$offerId:ID!,$q:String,$from:Time,$to:Time,$page:Int!,$perPage:Int!){franchiseOfferPriceRevisions(storeId:$storeId,offerId:$offerId,q:$q,from:$from,to:$to,page:$page,perPage:$perPage){data{id oldPriceFen newPriceFen reasonCode effectiveAt} total currentPage perPage}}`, ai.ModeReadOnly, "LOW", "franchiseProduct:read", franchise, "", nil, []string{"storeId", "offerId", "q", "from", "to", "page", "perPage"}),
		reviewedSpec("FranchiseStockBatches", "graphql.query.franchiseStockBatches", `query FranchiseStockBatches($storeId:ID!,$listingId:ID,$q:String,$sellable:Boolean,$page:Int!,$perPage:Int!){franchiseStockBatches(storeId:$storeId,listingId:$listingId,q:$q,sellable:$sellable,page:$page,perPage:$perPage){data{id listingId skuId productName skuName batchNumber producedAt expiresAt sellable packages{id name enabled containsPackageId containsQuantity packageSetVersion} balances{packageId quantity}} total currentPage perPage}}`, ai.ModeReadOnly, "LOW", "franchiseStock:read", franchise, "", nil, []string{"storeId", "listingId", "q", "sellable", "page", "perPage"}),
		reviewedSpec("FranchiseStockMovements", "graphql.query.franchiseStockMovements", `query FranchiseStockMovements($storeId:ID!,$batchId:ID!,$kind:StockMovementKind,$from:Time,$to:Time,$page:Int!,$perPage:Int!){franchiseStockMovements(storeId:$storeId,batchId:$batchId,kind:$kind,from:$from,to:$to,page:$page,perPage:$perPage){data{id batchId kind requestKey sourcePackageId targetPackageId sourceQuantity targetQuantity occurredAt} total currentPage perPage}}`, ai.ModeReadOnly, "LOW", "franchiseStock:read", franchise, "", nil, []string{"storeId", "batchId", "kind", "from", "to", "page", "perPage"}),
		reviewedSpec("FranchisePromotions", "graphql.query.franchisePromotions", `query FranchisePromotions($storeId:ID!,$kind:StorePromotionKind,$enabled:Boolean,$page:Int!,$perPage:Int!){franchisePromotions(storeId:$storeId,kind:$kind,enabled:$enabled,page:$page,perPage:$perPage){data{id storeId ruleKey version kind enabled startsAt endsAt checkoutUnavailable targets{offerId requiredQuantity}} total currentPage perPage}}`, ai.ModeReadOnly, "LOW", "franchisePromotion:read", franchise, "", nil, []string{"storeId", "kind", "enabled", "page", "perPage"}),
		reviewedSpec("FranchiseCouponMember", "graphql.query.franchiseCouponMember", `query FranchiseCouponMember($storeId:ID!,$identifier:String!){franchiseCouponMember(storeId:$storeId,identifier:$identifier){id memberNumber phoneMasked}}`, ai.ModeReadOnly, "HIGH", "franchiseCoupon:read", franchise, "", nil, []string{"storeId", "identifier"}),
		reviewedSpec("FranchiseCouponTemplates", "graphql.query.franchiseCouponTemplates", `query FranchiseCouponTemplates($storeId:ID!,$q:String,$enabled:Boolean,$page:Int!,$perPage:Int!){franchiseCouponTemplates(storeId:$storeId,q:$q,enabled:$enabled,page:$page,perPage:$perPage){data{id storeId code title amountFen minSpendFen daysAfterActivation effectiveAt distributionEndsAt perMemberLimit totalIssueLimit issuedCount enabled issuerScope} total currentPage perPage}}`, ai.ModeReadOnly, "LOW", "franchiseCoupon:read", franchise, "", nil, []string{"storeId", "q", "enabled", "page", "perPage"}),
		reviewedSpec("FranchiseCouponGrants", "graphql.query.franchiseCouponGrants", `query FranchiseCouponGrants($storeId:ID!,$templateId:ID!,$status:CustomerCouponGrantStatus,$page:Int!,$perPage:Int!){franchiseCouponGrants(storeId:$storeId,templateId:$templateId,status:$status,page:$page,perPage:$perPage){data{id templateId memberId status amountFen issuedAt revokedAt} total currentPage perPage}}`, ai.ModeReadOnly, "LOW", "franchiseCoupon:read", franchise, "", nil, []string{"storeId", "templateId", "status", "page", "perPage"}),
	}, append(productTemplateReadSpecs(), stocktakeReadSpecs()...)...)
}
